apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      tier: backend
  template:
    metadata:
      labels:
        app: app2
        tier: backend
    spec:
      containers:
      - name: app2
        image: mizdocker/bsapp2:latest
        ports:
        - containerPort: 5000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh"]
      nodeSelector:
        app2-deploy: "true"